specVersion: 1.0.0
name: subql-octopus
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: '>=2.5.4'
  query:
    name: '@subql/query'
    version: '*'
description: This project can be use as a starting po...
repository: https://github.com/octopus-appchains/subql-atocha.git
schema:
  file: ./schema.graphql
network:
  endpoint: >-
    wss://gateway.mainnet.octopus.network/fusotao/0efwa9v0crdx4dg3uj8jdmc5y7dj4ir2
  genesisHash: '0xa7113159e275582ee71ee499b24378a2416f34dc5aaf714443f0d11c6c3d99d3'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleAppchainToNearAccount
          kind: substrate/EventHandler
          filter:
            module: octopusLpos
            method: PlanNewEra
        - handler: handleAppchainToNearAccount
          kind: substrate/EventHandler
          filter:
            module: octopusLpos
            method: EraPayout
        - handler: handleAppchainToNearAccount
          kind: substrate/EventHandler
          filter:
            module: octopusAppchain
            method: Locked
        - handler: handleAppchainToNearAccount
          kind: substrate/EventHandler
          filter:
            module: octopusAppchain
            method: AssetBurned
        - handler: handleAppchainToNearAccount
          kind: substrate/EventHandler
          filter:
            module: octopusAppchain
            method: NftLocked
        - handler: handleAppchainToNearAccount
          kind: substrate/EventHandler
          filter:
            module: octopusBridge
            method: Locked
        - handler: handleAppchainToNearAccount
          kind: substrate/EventHandler
          filter:
            module: octopusBridge
            method: Nep141Burned
        - handler: handleAppchainToNearAccount
          kind: substrate/EventHandler
          filter:
            module: octopusBridge
            method: NonfungibleLocked
        - handler: handleNearToAppchainAccount
          kind: substrate/EventHandler
          filter:
            module: octopusBridge
            method: Unlocked
        - handler: handleNearToAppchainAccount
          kind: substrate/EventHandler
          filter:
            module: octopusBridge
            method: Nep141Minted
        - handler: handleNearToAppchainAccount
          kind: substrate/EventHandler
          filter:
            module: octopusBridge
            method: NonfungibleUnlocked
        - handler: handleNearToAppchainAccount
          kind: substrate/EventHandler
          filter:
            module: octopusBridge
            method: AssetMintFailed
        - handler: handleNearToAppchainAccount
          kind: substrate/EventHandler
          filter:
            module: octopusBridge
            method: AssetMinted
        - handler: handleNearToAppchainAccount
          kind: substrate/EventHandler
          filter:
            module: octopusBridge
            method: UnlockFailed
        - handler: handleNearToAppchainAccount
          kind: substrate/EventHandler
          filter:
            module: octopusBridge
            method: NftUnlockFailed
        - handler: handleNearToAppchainAccount
          kind: substrate/EventHandler
          filter:
            module: octopusBridge
            method: NftUnlocked
        - handler: handleNearToAppchainAccount
          kind: substrate/EventHandler
          filter:
            module: octopusBridge
            method: UnlockNonfungibleFailed
